id = "odoo-zed-snippets"
name = "Odoo Zed Snippets"
description = "Custom code snippets for Odoo development"
version = "0.1.0"
schema_version = 1
authors = ["Peter Preeper <ppreeper@gmail.com>"]
repository = "https://github.com/ppreeper/odoo-zed-snippets"

[snippets]
javascript = "snippets/javascript.json"
python = "snippets/python.json"
xml = "snippets/xml.json"
